"""simplified the event storage model

Revision ID: b4bfd0ea2fcc
Revises: c8ba5996e3bc
Create Date: 2016-01-19 11:21:36.801022

"""

# revision identifiers, used by Alembic.
revision = 'b4bfd0ea2fcc'
down_revision = 'c8ba5996e3bc'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('events_event_id_key', 'events', type_='unique')
    op.drop_column('events', 'service_id')
    op.drop_column('events', 'event_id')
    op.drop_column('events', 'user_id')
    op.drop_column('events', 'meta')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('meta', postgresql.JSONB(), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('user_id', sa.BIGINT(), server_default=sa.text("'1'::bigint"), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('event_id', sa.BIGINT(), server_default=sa.text("nextval('mds_event_id_seq'::regclass)"), nullable=False))
    op.add_column('events', sa.Column('service_id', sa.BIGINT(), server_default=sa.text("'1'::bigint"), autoincrement=False, nullable=False))
    op.create_unique_constraint('events_event_id_key', 'events', ['event_id'])
    ### end Alembic commands ###
