"""empty message

Revision ID: c8ba5996e3bc
Revises: 
Create Date: 2016-01-10 15:19:14.056417

"""

# revision identifiers, used by Alembic.
revision = 'c8ba5996e3bc'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SEQUENCE mds_object_id_seq")
    op.execute("CREATE SEQUENCE mds_event_id_seq")

    op.create_table('sources',
    sa.Column('aggregate_type', sa.String(), nullable=False),
    sa.Column('aggregate_id', postgresql.UUID(), nullable=False),
    sa.Column('object_id', sa.BigInteger(), server_default=sa.text("nextval('mds_object_id_seq')"), nullable=False),
    sa.Column('version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('aggregate_id'),
    sa.UniqueConstraint('object_id')
    )
    op.create_table('events',
    sa.Column('aggregate_id', postgresql.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), server_default=sa.text("nextval('mds_event_id_seq')"), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('dispatched', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), server_default='1', nullable=False),
    sa.Column('service_id', sa.BigInteger(), server_default='1', nullable=False),
    sa.Column('parameters', postgresql.JSONB(), nullable=False),
    sa.Column('meta', postgresql.JSONB(), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['aggregate_id'], ['sources.aggregate_id'], ),
    sa.PrimaryKeyConstraint('aggregate_id', 'version'),
    sa.UniqueConstraint('event_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    op.drop_table('sources')
    ### end Alembic commands ###
