Document: fulcrum-mds
Title: Debian fulcrum-mds Manual
Author: <insert document author here>
Abstract: This manual describes what fulcrum-mds is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/fulcrum-mds/fulcrum-mds.sgml.gz

Format: postscript
Files: /usr/share/doc/fulcrum-mds/fulcrum-mds.ps.gz

Format: text
Files: /usr/share/doc/fulcrum-mds/fulcrum-mds.text.gz

Format: HTML
Index: /usr/share/doc/fulcrum-mds/html/index.html
Files: /usr/share/doc/fulcrum-mds/html/*.html
